[package]
name = "amanda"
version = "0.1.0"
authors = ["Xavier Gillard <xavier.gillard@uclouvain.be>"]
description = "Amanda the stripper, makes your code naked" 

[dependencies]
libc    = "0.2.0"
clap    = "2.32.0"
walkdir = "2.2.5"